### PR TITLE
#33 Make automatic coverage reporting 

### PR DESCRIPTION
**Pull request by reid-spencer**
* update scala compiler to 2.13.12
* update scoverage to latest version (needed to thwart a compiler-bridge build error)
* change scoverage settings to not fail if minimum %age not obtained
* add scoverage support to all modules
* change the `ci` github workflow to run coverage and save the results

### CODE REVIEW

**Review by JamesYopp — DISMISSED** [review]
LGTM

**Review by antagonist112358 — APPROVED** [review]
LGTM

**Comment by reid-spencer** [comment]
@JamesYopp - please rubber-stamp this. Neither Kevin nor I can re-review. Thanks

**Review by JamesYopp — APPROVED** [review]
approved

**Pull request merged**
