### PR TITLE
Cart, Order, and Product impl backend

### PR DESCRIPTION
**Pull request by antagonist112358**
Implements the shopping cart (Cart), orders (Orders), and product (Products) functionality needed in the K2SO demo.

The UI/FE facing contract looks like this:
```
    /************************
     * Shopping Cart Routes *
     ************************/

    rpc CreateCart(service3.api.CreateShoppingCart) returns (service3.api.ShoppingCartId);

    rpc GetCart(service3.api.GetShoppingCart) returns (service3.domain.Cart);

    rpc AddItemToCart(service3.api.AddLineItem) returns (google.protobuf.Empty);

    rpc RemoveItemFromCart(service3.api.RemoveLineItem) returns (google.protobuf.Empty);

    rpc StartCartCheckout(service3.api.StartCheckout) returns (service3.domain.CartDetails);

    rpc CompleteCartCheckout(service3.api.CompleteCheckout) returns (google.protobuf.Empty);

    /****************
     * Order Routes *
     ****************/

    rpc CreateOrderFromCart(service3.api.OrderFromCart) returns (service3.api.OrderConfirmation);

    rpc GetOrderById(service3.api.OrderById) returns (service3.domain.Order);

    /******************
     * Product Routes *
     ******************/

    rpc GetProducts(google.protobuf.Empty) returns (service3.api.ProductList);

    rpc GetProductBySKU(service3.api.SingleProductRequest) returns (common.domain.Product);

    rpc GetProductsBySKU(service3.api.MultipleProductsRequest) returns (service3.api.ProductList);
```

Note: all of the above routes require authenticated/authorized gRPC requests. Said another way, they only work for "logged in" users.

Where shopping carts can have line items added/removed from them and be transitioned into a checking out state, and finally a checked out state (after the order is created).

The workflow would look like this:

1. CreateCart
2. AddItemToCart...
3. (Optionally) RemoveItemFromCart...
4. StartCartCheckout
5. CreateOrderFromCart
6. CompleteCartCheckout

Note: on `StartCartCheckout` a more UI/FE friendly version of the shopping cart, sufficient for the UI to display, is returned.

Also implemented is functionality for abandonment (automatic, time-based, back-end controlled) of shopping carts which are created (or started checking out) but never completed.

(Final) note: this PR is _much_ larger than it could have been due to removing dead/unnecessary code copied over from the OTT project and general code cleanup.

### CODE REVIEW

**Comment by antagonist112358** [comment]
@AlexWeinstein92 - The Sonar code quality failure is concerning JSX/Typescript files.

I would appreciate some help there!

See: [Link](https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&pullRequest=95&id=improving-ottawa_kalix-improving-template)

**Comment by AlexWeinstein92** [comment]
@antagonist112358 just pushed tsx fixes

**Review by AlexWeinstein92 — APPROVED** [review]
Great work! No comments

**Review by reid-spencer — COMMENTED** [review]
I've gIven up. Too large. Many comments are about changes not related to this PR, like why things are still named "service1", "service2", "service3" but also many of the changes are eliminating/replacing those old names. 

I don't understand why we have "com/improving" package names for things like hashing.  There are many standard implementations of these things that could have been used.

**Review by AlexWeinstein92 — APPROVED** [review]

**Pull request merged**
